// Copyright (c) 2026 Konstantin Adamov. Licensed under MIT.

use super::UnicodeEntry;

pub struct UnicodeSet {
    pub unicode_sections: Vec<UnicodeEntry>,
    pub filtered_unicode_sections: Vec<UnicodeEntry>,
}

impl UnicodeSet {
    pub fn new() -> Self {
        let unicode_sections = vec![
            UnicodeEntry::new(0x0000, "Basic Latin", 0x007F, false),
            UnicodeEntry::new(0x0080, "Latin-1 Supplement", 0x00FF, false),
            UnicodeEntry::new(0x0100, "Latin Extended-A", 0x017F, false),
            UnicodeEntry::new(0x0180, "Latin Extended-B", 0x024F, false),
            UnicodeEntry::new(0x0250, "IPA Extensions", 0x02AF, false),
            UnicodeEntry::new(0x02B0, "Spacing Modifier Letters", 0x02FF, false),
            UnicodeEntry::new(0x0300, "Combining Diacritical Marks", 0x036F, false),
            UnicodeEntry::new(0x0370, "Greek and Coptic", 0x03FF, false),
            UnicodeEntry::new(0x0400, "Cyrillic", 0x04FF, false),
            UnicodeEntry::new(0x0500, "Cyrillic Supplement", 0x052F, false),
            UnicodeEntry::new(0x0530, "Armenian", 0x058F, false),
            UnicodeEntry::new(0x0590, "Hebrew", 0x05FF, false),
            UnicodeEntry::new(0x0600, "Arabic", 0x06FF, false),
            UnicodeEntry::new(0x0700, "Syriac", 0x074F, false),
            UnicodeEntry::new(0x0750, "Arabic Supplement", 0x077F, false),
            UnicodeEntry::new(0x0780, "Thaana", 0x07BF, false),
            UnicodeEntry::new(0x07C0, "NKo", 0x07FF, false),
            UnicodeEntry::new(0x0800, "Samaritan", 0x083F, false),
            UnicodeEntry::new(0x0840, "Mandaic", 0x085F, false),
            UnicodeEntry::new(0x0860, "Syriac Supplement", 0x086F, false),
            UnicodeEntry::new(0x0870, "Arabic Extended-B", 0x089F, false),
            UnicodeEntry::new(0x08A0, "Arabic Extended-A", 0x08FF, false),
            UnicodeEntry::new(0x0900, "Devanagari", 0x097F, false),
            UnicodeEntry::new(0x0980, "Bengali", 0x09FF, false),
            UnicodeEntry::new(0x0A00, "Gurmukhi", 0x0A7F, false),
            UnicodeEntry::new(0x0A80, "Gujarati", 0x0AFF, false),
            UnicodeEntry::new(0x0B00, "Oriya", 0x0B7F, false),
            UnicodeEntry::new(0x0B80, "Tamil", 0x0BFF, false),
            UnicodeEntry::new(0x0C00, "Telugu", 0x0C7F, false),
            UnicodeEntry::new(0x0C80, "Kannada", 0x0CFF, false),
            UnicodeEntry::new(0x0D00, "Malayalam", 0x0D7F, false),
            UnicodeEntry::new(0x0D80, "Sinhala", 0x0DFF, false),
            UnicodeEntry::new(0x0E00, "Thai", 0x0E7F, false),
            UnicodeEntry::new(0x0E80, "Lao", 0x0EFF, false),
            UnicodeEntry::new(0x0F00, "Tibetan", 0x0FFF, false),
            UnicodeEntry::new(0x1000, "Myanmar", 0x109F, false),
            UnicodeEntry::new(0x10A0, "Georgian", 0x10FF, false),
            UnicodeEntry::new(0x1100, "Hangul Jamo", 0x11FF, false),
            UnicodeEntry::new(0x1200, "Ethiopic", 0x137F, false),
            UnicodeEntry::new(0x1380, "Ethiopic Supplement", 0x139F, false),
            UnicodeEntry::new(0x13A0, "Cherokee", 0x13FF, false),
            UnicodeEntry::new(0x1400, "Unified Canadian Aboriginal Syllabics", 0x167F, false),
            UnicodeEntry::new(0x1680, "Ogham", 0x169F, false),
            UnicodeEntry::new(0x16A0, "Runic", 0x16FF, false),
            UnicodeEntry::new(0x1700, "Tagalog", 0x171F, false),
            UnicodeEntry::new(0x1720, "Hanunoo", 0x173F, false),
            UnicodeEntry::new(0x1740, "Buhid", 0x175F, false),
            UnicodeEntry::new(0x1760, "Tagbanwa", 0x177F, false),
            UnicodeEntry::new(0x1780, "Khmer", 0x17FF, false),
            UnicodeEntry::new(0x1800, "Mongolian", 0x18AF, false),
            UnicodeEntry::new(
                0x18B0,
                "Unified Canadian Aboriginal Syllabics Extended",
                0x18FF,
                false,
            ),
            UnicodeEntry::new(0x1900, "Limbu", 0x194F, false),
            UnicodeEntry::new(0x1950, "Tai Le", 0x197F, false),
            UnicodeEntry::new(0x1980, "New Tai Lue", 0x19DF, false),
            UnicodeEntry::new(0x19E0, "Khmer Symbols", 0x19FF, false),
            UnicodeEntry::new(0x1A00, "Buginese", 0x1A1F, false),
            UnicodeEntry::new(0x1A20, "Tai Tham", 0x1AAF, false),
            UnicodeEntry::new(0x1AB0, "Combining Diacritical Marks Extended", 0x1AFF, false),
            UnicodeEntry::new(0x1B00, "Balinese", 0x1B7F, false),
            UnicodeEntry::new(0x1B80, "Sundanese", 0x1BBF, false),
            UnicodeEntry::new(0x1BC0, "Batak", 0x1BFF, false),
            UnicodeEntry::new(0x1C00, "Lepcha", 0x1C4F, false),
            UnicodeEntry::new(0x1C50, "Ol Chiki", 0x1C7F, false),
            UnicodeEntry::new(0x1C80, "Cyrillic Extended-C", 0x1C8F, false),
            UnicodeEntry::new(0x1C90, "Georgian Extended", 0x1CBF, false),
            UnicodeEntry::new(0x1CC0, "Sundanese Supplement", 0x1CCF, false),
            UnicodeEntry::new(0x1CD0, "Vedic Extensions", 0x1CFF, false),
            UnicodeEntry::new(0x1D00, "Phonetic Extensions", 0x1D7F, false),
            UnicodeEntry::new(0x1D80, "Phonetic Extensions Supplement", 0x1DBF, false),
            UnicodeEntry::new(0x1DC0, "Combining Diacritical Marks Supplement", 0x1DFF, false),
            UnicodeEntry::new(0x1E00, "Latin Extended Additional", 0x1EFF, false),
            UnicodeEntry::new(0x1F00, "Greek Extended", 0x1FFF, false),
            UnicodeEntry::new(0x2000, "General Punctuation", 0x206F, false),
            UnicodeEntry::new(0x2070, "Superscripts and Subscripts", 0x209F, false),
            UnicodeEntry::new(0x20A0, "Currency Symbols", 0x20CF, false),
            UnicodeEntry::new(
                0x20D0,
                "Combining Diacritical Marks for Symbols",
                0x20FF,
                false,
            ),
            UnicodeEntry::new(0x2100, "Letterlike Symbols", 0x214F, false),
            UnicodeEntry::new(0x2150, "Number Forms", 0x218F, false),
            UnicodeEntry::new(0x2190, "Arrows", 0x21FF, false),
            UnicodeEntry::new(0x2200, "Mathematical Operators", 0x22FF, false),
            UnicodeEntry::new(0x2300, "Miscellaneous Technical", 0x23FF, false),
            UnicodeEntry::new(0x2400, "Control Pictures", 0x243F, false),
            UnicodeEntry::new(0x2440, "Optical Character Recognition", 0x245F, false),
            UnicodeEntry::new(0x2460, "Enclosed Alphanumerics", 0x24FF, false),
            UnicodeEntry::new(0x2500, "Box Drawing", 0x257F, false),
            UnicodeEntry::new(0x2580, "Block Elements", 0x259F, false),
            UnicodeEntry::new(0x25A0, "Geometric Shapes", 0x25FF, false),
            UnicodeEntry::new(0x2600, "Miscellaneous Symbols", 0x26FF, false),
            UnicodeEntry::new(0x2700, "Dingbats", 0x27BF, false),
            UnicodeEntry::new(
                0x27C0,
                "Miscellaneous Mathematical Symbols-A",
                0x27EF,
                false,
            ),
            UnicodeEntry::new(0x27F0, "Supplemental Arrows-A", 0x27FF, false),
            UnicodeEntry::new(0x2800, "Braille Patterns", 0x28FF, false),
            UnicodeEntry::new(0x2900, "Supplemental Arrows-B", 0x297F, false),
            UnicodeEntry::new(
                0x2980,
                "Miscellaneous Mathematical Symbols-B",
                0x29FF,
                false,
            ),
            UnicodeEntry::new(0x2A00, "Supplemental Mathematical Operators", 0x2AFF, false),
            UnicodeEntry::new(0x2B00, "Miscellaneous Symbols and Arrows", 0x2BFF, false),
            UnicodeEntry::new(0x2C00, "Glagolitic", 0x2C5F, false),
            UnicodeEntry::new(0x2C60, "Latin Extended-C", 0x2C7F, false),
            UnicodeEntry::new(0x2C80, "Coptic", 0x2CFF, false),
            UnicodeEntry::new(0x2D00, "Georgian Supplement", 0x2D2F, false),
            UnicodeEntry::new(0x2D30, "Tifinagh", 0x2D7F, false),
            UnicodeEntry::new(0x2D80, "Ethiopic Extended", 0x2DDF, false),
            UnicodeEntry::new(0x2DE0, "Cyrillic Extended-A", 0x2DFF, false),
            UnicodeEntry::new(0x2E00, "Supplemental Punctuation", 0x2E7F, false),
            UnicodeEntry::new(0x2E80, "CJK Radicals Supplement", 0x2EFF, false),
            UnicodeEntry::new(0x2F00, "Kangxi Radicals", 0x2FDF, false),
            UnicodeEntry::new(0x2FF0, "Ideographic Description Characters", 0x2FFF, false),
            UnicodeEntry::new(0x3000, "CJK Symbols and Punctuation", 0x303F, false),
            UnicodeEntry::new(0x3040, "Hiragana", 0x309F, false),
            UnicodeEntry::new(0x30A0, "Katakana", 0x30FF, false),
            UnicodeEntry::new(0x3100, "Bopomofo", 0x312F, false),
            UnicodeEntry::new(0x3130, "Hangul Compatibility Jamo", 0x318F, false),
            UnicodeEntry::new(0x3190, "Kanbun", 0x319F, false),
            UnicodeEntry::new(0x31A0, "Bopomofo Extended", 0x31BF, false),
            UnicodeEntry::new(0x31C0, "CJK Strokes", 0x31EF, false),
            UnicodeEntry::new(0x31F0, "Katakana Phonetic Extensions", 0x31FF, false),
            UnicodeEntry::new(0x3200, "Enclosed CJK Letters and Months", 0x32FF, false),
            UnicodeEntry::new(0x3300, "CJK Compatibility", 0x33FF, false),
            UnicodeEntry::new(0x3400, "CJK Unified Ideographs Extension A", 0x4DBF, false),
            UnicodeEntry::new(0x4DC0, "Yijing Hexagram Symbols", 0x4DFF, false),
            UnicodeEntry::new(0x4E00, "CJK Unified Ideographs", 0x9FFF, false),
            UnicodeEntry::new(0xA000, "Yi Syllables", 0xA48F, false),
            UnicodeEntry::new(0xA490, "Yi Radicals", 0xA4CF, false),
            UnicodeEntry::new(0xA4D0, "Lisu", 0xA4FF, false),
            UnicodeEntry::new(0xA500, "Vai", 0xA63F, false),
            UnicodeEntry::new(0xA640, "Cyrillic Extended-B", 0xA69F, false),
            UnicodeEntry::new(0xA6A0, "Bamum", 0xA6FF, false),
            UnicodeEntry::new(0xA700, "Modifier Tone Letters", 0xA71F, false),
            UnicodeEntry::new(0xA720, "Latin Extended-D", 0xA7FF, false),
            UnicodeEntry::new(0xA800, "Syloti Nagri", 0xA82F, false),
            UnicodeEntry::new(0xA830, "Common Indic Number Forms", 0xA83F, false),
            UnicodeEntry::new(0xA840, "Phags-pa", 0xA87F, false),
            UnicodeEntry::new(0xA880, "Saurashtra", 0xA8DF, false),
            UnicodeEntry::new(0xA8E0, "Devanagari Extended", 0xA8FF, false),
            UnicodeEntry::new(0xA900, "Kayah Li", 0xA92F, false),
            UnicodeEntry::new(0xA930, "Rejang", 0xA95F, false),
            UnicodeEntry::new(0xA960, "Hangul Jamo Extended-A", 0xA97F, false),
            UnicodeEntry::new(0xA980, "Javanese", 0xA9DF, false),
            UnicodeEntry::new(0xA9E0, "Myanmar Extended-B", 0xA9FF, false),
            UnicodeEntry::new(0xAA00, "Cham", 0xAA5F, false),
            UnicodeEntry::new(0xAA60, "Myanmar Extended-A", 0xAA7F, false),
            UnicodeEntry::new(0xAA80, "Tai Viet", 0xAADF, false),
            UnicodeEntry::new(0xAAE0, "Meetei Mayek Extensions", 0xAAFF, false),
            UnicodeEntry::new(0xAB00, "Ethiopic Extended-A", 0xAB2F, false),
            UnicodeEntry::new(0xAB30, "Latin Extended-E", 0xAB6F, false),
            UnicodeEntry::new(0xAB70, "Cherokee Supplement", 0xABBF, false),
            UnicodeEntry::new(0xABC0, "Meetei Mayek", 0xABFF, false),
            UnicodeEntry::new(0xAC00, "Hangul Syllables", 0xD7AF, false),
            UnicodeEntry::new(0xD7B0, "Hangul Jamo Extended-B", 0xD7FF, false),
            UnicodeEntry::new(0xD800, "High Surrogates", 0xDB7F, false),
            UnicodeEntry::new(0xDB80, "High Private Use Surrogates", 0xDBFF, false),
            UnicodeEntry::new(0xDC00, "Low Surrogates", 0xDFFF, false),
            UnicodeEntry::new(0xE000, "Private Use Area", 0xF8FF, false),
            UnicodeEntry::new(0xF900, "CJK Compatibility Ideographs", 0xFAFF, false),
            UnicodeEntry::new(0xFB00, "Alphabetic Presentation Forms", 0xFB4F, false),
            UnicodeEntry::new(0xFB50, "Arabic Presentation Forms-A", 0xFDFF, false),
            UnicodeEntry::new(0xFE00, "Variation Selectors", 0xFE0F, false),
            UnicodeEntry::new(0xFE10, "Vertical Forms", 0xFE1F, false),
            UnicodeEntry::new(0xFE20, "Combining Half Marks", 0xFE2F, false),
            UnicodeEntry::new(0xFE30, "CJK Compatibility Forms", 0xFE4F, false),
            UnicodeEntry::new(0xFE50, "Small Form Variants", 0xFE6F, false),
            UnicodeEntry::new(0xFE70, "Arabic Presentation Forms-B", 0xFEFF, false),
            UnicodeEntry::new(0xFF00, "Halfwidth and Fullwidth Forms", 0xFFEF, false),
            UnicodeEntry::new(0xFFF0, "Specials", 0xFFFF, false),
            UnicodeEntry::new(0x10000, "Linear B Syllabary", 0x1007F, false),
            UnicodeEntry::new(0x10080, "Linear B Ideograms", 0x100FF, false),
            UnicodeEntry::new(0x10100, "Aegean Numbers", 0x1013F, false),
            UnicodeEntry::new(0x10140, "Ancient Greek Numbers", 0x1018F, false),
            UnicodeEntry::new(0x10190, "Ancient Symbols", 0x101CF, false),
            UnicodeEntry::new(0x101D0, "Phaistos Disc", 0x101FF, false),
            UnicodeEntry::new(0x10280, "Lycian", 0x1029F, false),
            UnicodeEntry::new(0x102A0, "Carian", 0x102DF, false),
            UnicodeEntry::new(0x102E0, "Coptic Epact Numbers", 0x102FF, false),
            UnicodeEntry::new(0x10300, "Old Italic", 0x1032F, false),
            UnicodeEntry::new(0x10330, "Gothic", 0x1034F, false),
            UnicodeEntry::new(0x10350, "Old Permic", 0x1037F, false),
            UnicodeEntry::new(0x10380, "Ugaritic", 0x1039F, false),
            UnicodeEntry::new(0x103A0, "Old Persian", 0x103DF, false),
            UnicodeEntry::new(0x10400, "Deseret", 0x1044F, false),
            UnicodeEntry::new(0x10450, "Shavian", 0x1047F, false),
            UnicodeEntry::new(0x10480, "Osmanya", 0x104AF, false),
            UnicodeEntry::new(0x104B0, "Osage", 0x104FF, false),
            UnicodeEntry::new(0x10500, "Elbasan", 0x1052F, false),
            UnicodeEntry::new(0x10530, "Caucasian Albanian", 0x1056F, false),
            UnicodeEntry::new(0x10570, "Vithkuqi", 0x105BF, false),
            UnicodeEntry::new(0x105C0, "Todhri", 0x105FF, false),
            UnicodeEntry::new(0x10600, "Linear A", 0x1077F, false),
            UnicodeEntry::new(0x10780, "Latin Extended-F", 0x107BF, false),
            UnicodeEntry::new(0x10800, "Cypriot Syllabary", 0x1083F, false),
            UnicodeEntry::new(0x10840, "Imperial Aramaic", 0x1085F, false),
            UnicodeEntry::new(0x10860, "Palmyrene", 0x1087F, false),
            UnicodeEntry::new(0x10880, "Nabataean", 0x108AF, false),
            UnicodeEntry::new(0x108E0, "Hatran", 0x108FF, false),
            UnicodeEntry::new(0x10900, "Phoenician", 0x1091F, false),
            UnicodeEntry::new(0x10920, "Lydian", 0x1093F, false),
            UnicodeEntry::new(0x10940, "Sidetic", 0x1095F, false),
            UnicodeEntry::new(0x10980, "Meroitic Hieroglyphs", 0x1099F, false),
            UnicodeEntry::new(0x109A0, "Meroitic Cursive", 0x109FF, false),
            UnicodeEntry::new(0x10A00, "Kharoshthi", 0x10A5F, false),
            UnicodeEntry::new(0x10A60, "Old South Arabian", 0x10A7F, false),
            UnicodeEntry::new(0x10A80, "Old North Arabian", 0x10A9F, false),
            UnicodeEntry::new(0x10AC0, "Manichaean", 0x10AFF, false),
            UnicodeEntry::new(0x10B00, "Avestan", 0x10B3F, false),
            UnicodeEntry::new(0x10B40, "Inscriptional Parthian", 0x10B5F, false),
            UnicodeEntry::new(0x10B60, "Inscriptional Pahlavi", 0x10B7F, false),
            UnicodeEntry::new(0x10B80, "Psalter Pahlavi", 0x10BAF, false),
            UnicodeEntry::new(0x10C00, "Old Turkic", 0x10C4F, false),
            UnicodeEntry::new(0x10C80, "Old Hungarian", 0x10CFF, false),
            UnicodeEntry::new(0x10D00, "Hanifi Rohingya", 0x10D3F, false),
            UnicodeEntry::new(0x10D40, "Garay", 0x10D8F, false),
            UnicodeEntry::new(0x10E60, "Rumi Numeral Symbols", 0x10E7F, false),
            UnicodeEntry::new(0x10E80, "Yezidi", 0x10EBF, false),
            UnicodeEntry::new(0x10EC0, "Arabic Extended-C", 0x10EFF, false),
            UnicodeEntry::new(0x10F00, "Old Sogdian", 0x10F2F, false),
            UnicodeEntry::new(0x10F30, "Sogdian", 0x10F6F, false),
            UnicodeEntry::new(0x10F70, "Old Uyghur", 0x10FAF, false),
            UnicodeEntry::new(0x10FB0, "Chorasmian", 0x10FDF, false),
            UnicodeEntry::new(0x10FE0, "Elymaic", 0x10FFF, false),
            UnicodeEntry::new(0x11000, "Brahmi", 0x1107F, false),
            UnicodeEntry::new(0x11080, "Kaithi", 0x110CF, false),
            UnicodeEntry::new(0x110D0, "Sora Sompeng", 0x110FF, false),
            UnicodeEntry::new(0x11100, "Chakma", 0x1114F, false),
            UnicodeEntry::new(0x11150, "Mahajani", 0x1117F, false),
            UnicodeEntry::new(0x11180, "Sharada", 0x111DF, false),
            UnicodeEntry::new(0x111E0, "Sinhala Archaic Numbers", 0x111FF, false),
            UnicodeEntry::new(0x11200, "Khojki", 0x1124F, false),
            UnicodeEntry::new(0x11280, "Multani", 0x112AF, false),
            UnicodeEntry::new(0x112B0, "Khudawadi", 0x112FF, false),
            UnicodeEntry::new(0x11300, "Grantha", 0x1137F, false),
            UnicodeEntry::new(0x11380, "Tulu-Tigalari", 0x113FF, false),
            UnicodeEntry::new(0x11400, "Newa", 0x1147F, false),
            UnicodeEntry::new(0x11480, "Tirhuta", 0x114DF, false),
            UnicodeEntry::new(0x11580, "Siddham", 0x115FF, false),
            UnicodeEntry::new(0x11600, "Modi", 0x1165F, false),
            UnicodeEntry::new(0x11660, "Mongolian Supplement", 0x1167F, false),
            UnicodeEntry::new(0x11680, "Takri", 0x116CF, false),
            UnicodeEntry::new(0x116D0, "Myanmar Extended-C", 0x116FF, false),
            UnicodeEntry::new(0x11700, "Ahom", 0x1174F, false),
            UnicodeEntry::new(0x11800, "Dogra", 0x1184F, false),
            UnicodeEntry::new(0x118A0, "Warang Citi", 0x118FF, false),
            UnicodeEntry::new(0x11900, "Dives Akuru", 0x1195F, false),
            UnicodeEntry::new(0x119A0, "Nandinagari", 0x119FF, false),
            UnicodeEntry::new(0x11A00, "Zanabazar Square", 0x11A4F, false),
            UnicodeEntry::new(0x11A50, "Soyombo", 0x11AAF, false),
            UnicodeEntry::new(
                0x11AB0,
                "Unified Canadian Aboriginal Syllabics Extended-A",
                0x11ABF,
                false,
            ),
            UnicodeEntry::new(0x11AC0, "Pau Cin Hau", 0x11AFF, false),
            UnicodeEntry::new(0x11B00, "Devanagari Extended-A", 0x11B5F, false),
            UnicodeEntry::new(0x11B60, "Sharada Supplement", 0x11B7F, false),
            UnicodeEntry::new(0x11BC0, "Sunuwar", 0x11BFF, false),
            UnicodeEntry::new(0x11C00, "Bhaiksuki", 0x11C6F, false),
            UnicodeEntry::new(0x11C70, "Marchen", 0x11CBF, false),
            UnicodeEntry::new(0x11D00, "Masaram Gondi", 0x11D5F, false),
            UnicodeEntry::new(0x11D60, "Gunjala Gondi", 0x11DAF, false),
            UnicodeEntry::new(0x11DB0, "Tolong Siki", 0x11DEF, false),
            UnicodeEntry::new(0x11EE0, "Makasar", 0x11EFF, false),
            UnicodeEntry::new(0x11F00, "Kawi", 0x11F5F, false),
            UnicodeEntry::new(0x11FB0, "Lisu Supplement", 0x11FBF, false),
            UnicodeEntry::new(0x11FC0, "Tamil Supplement", 0x11FFF, false),
            UnicodeEntry::new(0x12000, "Cuneiform", 0x123FF, false),
            UnicodeEntry::new(0x12400, "Cuneiform Numbers and Punctuation", 0x1247F, false),
            UnicodeEntry::new(0x12480, "Early Dynastic Cuneiform", 0x1254F, false),
            UnicodeEntry::new(0x12F90, "Cypro-Minoan", 0x12FFF, false),
            UnicodeEntry::new(0x13000, "Egyptian Hieroglyphs", 0x1342F, false),
            UnicodeEntry::new(
                0x13430,
                "Egyptian Hieroglyph Format Controls",
                0x1345F,
                false,
            ),
            UnicodeEntry::new(0x13460, "Egyptian Hieroglyphs Extended-A", 0x143FF, false),
            UnicodeEntry::new(0x14400, "Anatolian Hieroglyphs", 0x1467F, false),
            UnicodeEntry::new(0x16100, "Gurung Khema", 0x1613F, false),
            UnicodeEntry::new(0x16800, "Bamum Supplement", 0x16A3F, false),
            UnicodeEntry::new(0x16A40, "Mro", 0x16A6F, false),
            UnicodeEntry::new(0x16A70, "Tangsa", 0x16ACF, false),
            UnicodeEntry::new(0x16AD0, "Bassa Vah", 0x16AFF, false),
            UnicodeEntry::new(0x16B00, "Pahawh Hmong", 0x16B8F, false),
            UnicodeEntry::new(0x16D40, "Kirat Rai", 0x16D7F, false),
            UnicodeEntry::new(0x16E40, "Medefaidrin", 0x16E9F, false),
            UnicodeEntry::new(0x16EA0, "Beria Erfe", 0x16EDF, false),
            UnicodeEntry::new(0x16F00, "Miao", 0x16F9F, false),
            UnicodeEntry::new(
                0x16FE0,
                "Ideographic Symbols and Punctuation",
                0x16FFF,
                false,
            ),
            UnicodeEntry::new(0x17000, "Tangut", 0x187FF, false),
            UnicodeEntry::new(0x18800, "Tangut Components", 0x18AFF, false),
            UnicodeEntry::new(0x18B00, "Khitan Small Script", 0x18CFF, false),
            UnicodeEntry::new(0x18D00, "Tangut Supplement", 0x18D7F, false),
            UnicodeEntry::new(0x18D80, "Tangut Components Supplement", 0x18DFF, false),
            UnicodeEntry::new(0x1AFF0, "Kana Extended-B", 0x1AFFF, false),
            UnicodeEntry::new(0x1B000, "Kana Supplement", 0x1B0FF, false),
            UnicodeEntry::new(0x1B100, "Kana Extended-A", 0x1B12F, false),
            UnicodeEntry::new(0x1B130, "Small Kana Extension", 0x1B16F, false),
            UnicodeEntry::new(0x1B170, "Nushu", 0x1B2FF, false),
            UnicodeEntry::new(0x1BC00, "Duployan", 0x1BC9F, false),
            UnicodeEntry::new(0x1BCA0, "Shorthand Format Controls", 0x1BCAF, false),
            UnicodeEntry::new(
                0x1CC00,
                "Symbols for Legacy Computing Supplement",
                0x1CEBF,
                false,
            ),
            UnicodeEntry::new(0x1CEC0, "Miscellaneous Symbols Supplement", 0x1CEFF, false),
            UnicodeEntry::new(0x1CF00, "Znamenny Musical Notation", 0x1CFCF, false),
            UnicodeEntry::new(0x1D000, "Byzantine Musical Symbols", 0x1D0FF, false),
            UnicodeEntry::new(0x1D100, "Musical Symbols", 0x1D1FF, false),
            UnicodeEntry::new(0x1D200, "Ancient Greek Musical Notation", 0x1D24F, false),
            UnicodeEntry::new(0x1D2C0, "Kaktovik Numerals", 0x1D2DF, false),
            UnicodeEntry::new(0x1D2E0, "Mayan Numerals", 0x1D2FF, false),
            UnicodeEntry::new(0x1D300, "Tai Xuan Jing Symbols", 0x1D35F, false),
            UnicodeEntry::new(0x1D360, "Counting Rod Numerals", 0x1D37F, false),
            UnicodeEntry::new(0x1D400, "Mathematical Alphanumeric Symbols", 0x1D7FF, false),
            UnicodeEntry::new(0x1D800, "Sutton SignWriting", 0x1DAAF, false),
            UnicodeEntry::new(0x1DF00, "Latin Extended-G", 0x1DFFF, false),
            UnicodeEntry::new(0x1E000, "Glagolitic Supplement", 0x1E02F, false),
            UnicodeEntry::new(0x1E030, "Cyrillic Extended-D", 0x1E08F, false),
            UnicodeEntry::new(0x1E100, "Nyiakeng Puachue Hmong", 0x1E14F, false),
            UnicodeEntry::new(0x1E290, "Toto", 0x1E2BF, false),
            UnicodeEntry::new(0x1E2C0, "Wancho", 0x1E2FF, false),
            UnicodeEntry::new(0x1E4D0, "Nag Mundari", 0x1E4FF, false),
            UnicodeEntry::new(0x1E5D0, "Ol Onal", 0x1E5FF, false),
            UnicodeEntry::new(0x1E6C0, "Tai Yo", 0x1E6FF, false),
            UnicodeEntry::new(0x1E7E0, "Ethiopic Extended-B", 0x1E7FF, false),
            UnicodeEntry::new(0x1E800, "Mende Kikakui", 0x1E8DF, false),
            UnicodeEntry::new(0x1E900, "Adlam", 0x1E95F, false),
            UnicodeEntry::new(0x1EC70, "Indic Siyaq Numbers", 0x1ECBF, false),
            UnicodeEntry::new(0x1ED00, "Ottoman Siyaq Numbers", 0x1ED4F, false),
            UnicodeEntry::new(
                0x1EE00,
                "Arabic Mathematical Alphabetic Symbols",
                0x1EEFF,
                false,
            ),
            UnicodeEntry::new(0x1F000, "Mahjong Tiles", 0x1F02F, false),
            UnicodeEntry::new(0x1F030, "Domino Tiles", 0x1F09F, false),
            UnicodeEntry::new(0x1F0A0, "Playing Cards", 0x1F0FF, false),
            UnicodeEntry::new(0x1F100, "Enclosed Alphanumeric Supplement", 0x1F1FF, false),
            UnicodeEntry::new(0x1F200, "Enclosed Ideographic Supplement", 0x1F2FF, false),
            UnicodeEntry::new(
                0x1F300,
                "Miscellaneous Symbols and Pictographs",
                0x1F5FF,
                false,
            ),
            UnicodeEntry::new(0x1F600, "Emoticons", 0x1F64F, false),
            UnicodeEntry::new(0x1F650, "Ornamental Dingbats", 0x1F67F, false),
            UnicodeEntry::new(0x1F680, "Transport and Map Symbols", 0x1F6FF, false),
            UnicodeEntry::new(0x1F700, "Alchemical Symbols", 0x1F77F, false),
            UnicodeEntry::new(0x1F780, "Geometric Shapes Extended", 0x1F7FF, false),
            UnicodeEntry::new(0x1F800, "Supplemental Arrows-C", 0x1F8FF, false),
            UnicodeEntry::new(
                0x1F900,
                "Supplemental Symbols and Pictographs",
                0x1F9FF,
                false,
            ),
            UnicodeEntry::new(0x1FA00, "Chess Symbols", 0x1FA6F, false),
            UnicodeEntry::new(
                0x1FA70,
                "Symbols and Pictographs Extended-A",
                0x1FAFF,
                false,
            ),
            UnicodeEntry::new(0x1FB00, "Symbols for Legacy Computing", 0x1FBFF, false),
            UnicodeEntry::new(0x1FF80, "Unassigned", 0x1FFFF, false),
            UnicodeEntry::new(0x20000, "CJK Unified Ideographs Extension B", 0x2A6DF, false),
            UnicodeEntry::new(0x2A700, "CJK Unified Ideographs Extension C", 0x2B73F, false),
            UnicodeEntry::new(0x2B740, "CJK Unified Ideographs Extension D", 0x2B81F, false),
            UnicodeEntry::new(0x2B820, "CJK Unified Ideographs Extension E", 0x2CEAF, false),
            UnicodeEntry::new(0x2CEB0, "CJK Unified Ideographs Extension F", 0x2EBEF, false),
            UnicodeEntry::new(0x2EBF0, "CJK Unified Ideographs Extension I", 0x2EE5F, false),
            UnicodeEntry::new(
                0x2F800,
                "CJK Compatibility Ideographs Supplement",
                0x2FA1F,
                false,
            ),
            UnicodeEntry::new(0x30000, "CJK Unified Ideographs Extension G", 0x3134F, false),
            UnicodeEntry::new(0x31350, "CJK Unified Ideographs Extension H", 0x323AF, false),
            UnicodeEntry::new(0x323B0, "CJK Unified Ideographs Extension J", 0x3347F, false),
            UnicodeEntry::new(0xE0000, "Tags", 0xE007F, false),
            UnicodeEntry::new(0xE0100, "Variation Selectors Supplement", 0xE01EF, false),
            UnicodeEntry::new(0xEFF80, "Unassigned", 0xEFFFF, false),
            UnicodeEntry::new(0xFFF80, "Supplementary Private Use Area-A", 0xFFFFF, false),
            UnicodeEntry::new(
                0xF1000,
                "NearFont Supplementary Private Area",
                0xF1AF0,
                false,
            ),
            UnicodeEntry::new(0x10FF80, "Supplementary Private Use Area-B", 0x10FFFF, false),
            UnicodeEntry::new(
                0x100000,
                "Apple San Fracisco Private Section",
                0x1007BF,
                false,
            ),
        ];

        Self {
            unicode_sections,
            filtered_unicode_sections: Vec::new(),
        }
    }
}

impl Default for UnicodeSet {
    fn default() -> Self {
        Self::new()
    }
}
